version: '2'
services:
  grafana:
    image: hyperworks/grafana
    link:
      - influxdb
    port:
      - "3300:80"
    environment:
      INFLUXDB_HOST=influxdb
      INFLUXDB_PORT=8086
      INFLUX_NAME=metric
      INFLUX_USER=root
      INFLUX_PASS=root
  influxdb:
    image: tutum/influxdb
    ports:
      - "8086:8086"
      - "8083:8083"

